### PR TITLE
Add presentation by Cvrček and Fidler

### PR DESCRIPTION
**Pull request by lajanda**
Add presentation by Cvrček and Fidler: Threat defuser presentation March 2021-VC-MUF.pdf

### CODE REVIEW

**Comment by bast** [comment]
But are the files missing?

**Comment by lajanda** [comment]
Dear Radovan,

I apologize. I thought that I had uploaded the file in github, but maybe I made a mistake. Here it is.

Laura A. Janda
Professor, Institute for Language and Culture
UiT The Arctic University of Norway
My profile: https://uit.no/ansatte/person?p_document_id=41561
My homepage: http://ansatte.uit.no/laura.janda/

From: Radovan Bast ***@***.***>
Reply to: "threat-defuser/threat-defuser.org" ***@***.***>
Date: Thursday, 11 March 2021 at 21:49
To: "threat-defuser/threat-defuser.org" ***@***.***>
Cc: Laura A Janda ***@***.***>, Author ***@***.***>
Subject: Re: [threat-defuser/threat-defuser.org] Add presentation by Cvrček and Fidler (#56)


But are the files missing?

**Comment by bast** [comment]
Maybe the attachments get lost when you directly reply to email from GitHub. Can you perhaps send them to my email address (not replying to this message from GitHub) and I will then upload them?

**Comment by bast** [comment]
Solved in 45d3504a4efdd84974c18e2c.

**Pull request closed without merging**
