### PR TITLE
Add article by Cvrček and Fidler

### PR DESCRIPTION
**Pull request by lajanda**
Add the article on Market Basket Analysis. I have also attached this file: CvrcekFidler2021.pdf. I hope I did this correctly. Please check.

### CODE REVIEW

**Comment by bast** [comment]
The attachment part does not work. Can you please send it via email? And at some point we can make a session where I show how to attach the files there.

**Comment by bast** [comment]
You can see that this is not working if you click at "Files changed" only one file is modified, the markdown file. But we would expect two files to be modified: one added and one changed.

**Comment by lajanda** [comment]
Dear Radovan,

Here is the article that I thought I had uploaded. I apologize for being clumsy with this on github and look forward to learning how to do this better.

Laura A. Janda
Professor of Russian
UiT The Arctic University of Norway
https://uit.no/ansatte/person?p_document_id=41561
http://ansatte.uit.no/laura.janda/

________________________________

**Comment by bast** [comment]
The article is up: https://threat-defuser.org/results/

Here is how to add articles via web interface: https://github.com/threat-defuser/threat-defuser.org#how-to-upload-articles-or-presentations

**Comment by lajanda** [comment]
Thanks! I will try to do this correctly next time. 🙂

Laura A. Janda
Professor of Russian
UiT The Arctic University of Norway
https://uit.no/ansatte/person?p_document_id=41561
http://ansatte.uit.no/laura.janda/

________________________________

**Pull request closed without merging**
